Sync runner setup with official crave builder repo

diff --git a/.github/workflows/build_with_scripts.yml b/.github/workflows/build_with_scripts.yml
--- a/.github/workflows/build_with_scripts.yml
+++ b/.github/workflows/build_with_scripts.yml
@@ -35,27 +35,42 @@ jobs:
     - name: Checkout code
       uses: actions/checkout@v2
 
+    - name: Set up environment
+      run: |
+        sudo apt-get update
+        sudo apt-get install -y tmux
+
       # Download and configure 'crave'.
     - name: Configure the 'crave' environment
       run: |
-          mkdir ${HOME}/bin/
-          curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
-          mv ${PWD}/crave ${HOME}/bin/
-          sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
-          envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
-          rm -rf ${PWD}/crave.conf.sample
+        mkdir ${HOME}/bin/
+        curl -s https://raw.githubusercontent.com/accupara/crave/master/get_crave.sh | bash -s --
+        mv ${PWD}/crave ${HOME}/bin/
+        sudo ln -sf /home/${USER}/bin/crave /usr/bin/crave
+        envsubst < ${PWD}/crave.conf.sample >> ${PWD}/crave.conf
+        rm -rf ${PWD}/crave.conf.sample          
+
       env:
         CRAVE_USERNAME: ${{  secrets.CRAVE_USERNAME  }}
         CRAVE_TOKEN: ${{  secrets.CRAVE_TOKEN  }}
 
     - name: Run crave devspace
       run: |
-        crave -n devspace -- "if tmux has-session -t ghactions; then
-          echo "Runner is already Running"
-        else
+        crave devspace -- "echo "Looking for runner..."
+          # Look for whether there's a runner folder set up
+          if [ -f actions-runner/run.sh ] ; then
+            echo "Runner found! Restarting it..."
+          else
+            echo "Error! Runner not found!"
+            exit 1
+          fi
+
+        if tmux has-session -t ghactions; then 
+          echo "Runner is already Running" 
+        else 
           tmux kill-session -t ghactions;
-          tmux new-session -d -s ghactions
-          tmux send-keys -t ghactions './actions-runner/run.sh' Enter
+          tmux new-session -d -s ghactions 
+          tmux send-keys -t ghactions './actions-runner/run.sh' Enter 
           echo "Runner Started"
         fi "
 
