Decluttering and Refactor

diff --git a/.github/workflows/github_release_upload.yml b/.github/workflows/github_release_upload.yml
--- a/.github/workflows/github_release_upload.yml
+++ b/.github/workflows/github_release_upload.yml
@@ -64,7 +64,7 @@ jobs:
 
     steps:
 
-    - name: Build dir
+    - name: Initialize build directory
       run: |
         build_dir=$(crave clone list --json | jq -r '.clones[]."Cloned At"')
         echo "BUILD_DIR=$build_dir" >> $GITHUB_ENV
@@ -72,9 +72,9 @@ jobs:
     - name: Preparing ROM zip
       continue-on-error: false
       run: |
-        cd ${{ env.BUILD_DIR }}
+        cd ${{ env.BUILD_DIR }}/out
 
-            file_name=$(find "${{ env.BUILD_DIR }}/compiled/" -name '*.zip' | sed 's|.*/||')
+            file_name=$(find . -maxdepth 1 -name '*.zip' | sed 's|^\./||')
             release_title=$(basename "$file_name" .zip)
 
             echo "ZIP_FILE=$file_name" >> $GITHUB_ENV
@@ -83,7 +83,7 @@ jobs:
 
     - name: Upload to GitHub releases
       run: |
-        cd ${{ env.BUILD_DIR }}
+        cd ${{ env.BUILD_DIR }}/out
 
         NC='\033[0m'
         RED='\033[0;31m'
@@ -94,20 +94,23 @@ jobs:
            source ~/.config/envman/PATH.env
            echo "gh installed."
         fi
-
+        
+        if ! ls *.zip 1> /dev/null 2>&1; then
+          echo -e '\e[31mError! No zip file found. Run crave_pull.yml first!\e[0m'
+          exit 1
+        fi
+        
         gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}
 
-        if [[ -f "${{ env.BUILD_DIR }}/compiled/${{ env.ZIP_FILE }}" ]]; then
-           file_size=$(stat -c%s "${{ env.BUILD_DIR }}/compiled/${{ env.ZIP_FILE }}")
+        if [[ -f "${{ env.ZIP_FILE }}" ]]; then
+           file_size=$(stat -c%s "${{ env.ZIP_FILE }}")
            if [[ $file_size -le 2147483648 ]]; then
               gh release create ${{ github.run_id }} --repo ${{ github.repository }} --title ${{ env.RELEASENAME }} --notes "Released on ${{ env.RELEASE_DATE }}"
-              gh release upload ${{ github.run_id }} --repo ${{ github.repository }} ${{ env.BUILD_DIR }}/compiled/*
+              gh release upload ${{ github.run_id }} --repo ${{ github.repository }} ${{ env.BUILD_DIR }}/out/*
            else
-              echo -e ${RED} "#######################################################################"
-              echo -e ${RED} "##          ROM ZIP FILE IS TOO LARGE FOR GITHUB RELEASE!!           ##"
-              echo -e ${RED} "##         GO TO YOUR DEVSPACE AND UPLOAD IT SOMEWHERE ELSE          ##"
-              echo -e ${RED} "#######################################################################${NC}"
-              echo "FILE PATH: ${{ env.BUILD_DIR }}/compiled/${{ env.ZIP_FILE }}"
+              echo -e '\e[31mERROR! ROM zip file is too large for GitHub release!\e[0m'
+              echo -e '\e[31mGo to your devspace and upload it somewhere else!\e[0m'
+              echo "FILE PATH: ${{ env.BUILD_DIR }}/out/${{ env.ZIP_FILE }}"
               exit 1
            fi
         fi
