Colorized runner checks output
* So it can be seen easily in github action logs

diff --git a/.github/workflows/manual_upload_gdrive.yml b/.github/workflows/manual_upload_gdrive.yml
--- a/.github/workflows/manual_upload_gdrive.yml
+++ b/.github/workflows/manual_upload_gdrive.yml
@@ -43,22 +43,23 @@ jobs:
 
     - name: Run crave devspace
       run: |
-        crave devspace -- "echo "Looking for runner..."
+        crave devspace -- "
+        echo "Looking for runner..."
           # Look for whether there's a runner folder set up
-          if [ -f actions-runner/run.sh ] ; then
-            echo "Runner found! Restarting it..."
-          else
-            echo "Error! Runner not found!"
-            exit 1
-          fi
-
-        if tmux has-session -t ghactions; then
-          echo "Runner is already Running"
+        if [ -f actions-runner/run.sh ] ; then
+          echo -e '\e[32mRunner found! Restarting it...\e[0m'
         else
+          echo -e '\e[31mError! Runner not found!\e[0m'
+          exit 1
+        fi
+
+        if tmux has-session -t ghactions; then 
+          echo -e '\e[32mRunner is already Running\e[0m'
+        else 
           tmux kill-session -t ghactions;
-          tmux new-session -d -s ghactions
-          tmux send-keys -t ghactions './actions-runner/run.sh' Enter
-          echo "Runner Started"
+          tmux new-session -d -s ghactions 
+          tmux send-keys -t ghactions './actions-runner/run.sh' Enter 
+          echo -e '\e[32mRunner Started\e[0m'
         fi "
 
   upload:
